newspapers/urls.py
from django.urls import path

from newspapers.views import (
    index,
    TopicCreateView,
    TopicListView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperListView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorListView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDeleteView,
    NewspaperDetailView,
    RedactorDetailView
)

urlpatterns = [
    path("", index, name="index"),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
    path("topics/<int:pk>/update/", TopicUpdateView.as_view(), name="topic-update"),
    path("topics/<int:pk>/delete/", TopicDeleteView.as_view(), name="topic-delete"),
    path("newspapers/", NewspaperListView.as_view(), name="newspaper-list"),
    path("newspapers/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path("newspapers/<int:pk>/update/", NewspaperUpdateView.as_view(), name="newspaper-update"),
    path("newspapers/<int:pk>/delete/", NewspaperDeleteView.as_view(), name="newspaper-delete"),
    path("newspapers/<int:pk>/", NewspaperDetailView.as_view(), name="newspaper-detail"),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path("redactors/create/", RedactorCreateView.as_view(), name="redactor-create"),
    path("redactors/<int:pk>/update/", RedactorUpdateView.as_view(), name="redactor-update"),
    path("redactors/<int:pk>/delete/", RedactorDeleteView.as_view(), name="redactor-delete"),
    path("redactors/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"),
]

app_name = "newspapers"

newspapers/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models


class Topic(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ("name",)

    def __str__(self) -> str:
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(default=0, null=True, blank=True)

    class Meta:
        ordering = ("username",)

    def __str__(self) -> str:
        return f"{self.username} ({self.first_name} {self.last_name})"


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published_date = models.DateField(auto_now_add=True)
    topics = models.ManyToManyField(Topic, related_name="newspapers")
    publishers = models.ManyToManyField(
        get_user_model(), related_name="newspapers"
    )

    class Meta:
        ordering = ("title",)

    def __str__(self) -> str:
        return f"{self.title} ({', '.join([str(topic) for topic in self.topics.all()])})"

newspapers/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from newspapers.models import Newspaper, Redactor


class NewspaperForm(forms.ModelForm):
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class NewspaperTitleSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by title"}
        )
    )


class TopicNameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )


class RedactorUsernameSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by username"}
        )
    )


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
            "email"
        )

    def clean_years_of_experience(self) -> int:
        return int(
            validate_years_of_experience(
                self.cleaned_data["years_of_experience"]
            )
        )


class UserRegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name"
        )


class RedactorUpdateForm(forms.ModelForm):
    class Meta:
        model = Redactor
        fields = ("username", "first_name", "last_name", "years_of_experience", "email",)

    def clean_years_of_experience(self) -> int:
        return int(
            validate_years_of_experience(
                self.cleaned_data["years_of_experience"]
            )
        )


def validate_years_of_experience(
    years_of_experience: int | float
) -> int | float:
    if not isinstance(years_of_experience, (int, float)):
        raise ValidationError("Years of experience must be a number.")
    if not (years_of_experience >= 0):
        raise ValidationError(
            "Years of experience must be a non-negative number."
        )
    return years_of_experience

newspapers/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import FormView

from newspapers.models import Newspaper, Redactor, Topic

from newspapers.forms import (
    NewspaperTitleSearchForm,
    NewspaperForm,
    RedactorUsernameSearchForm,
    TopicNameSearchForm,
    RedactorCreationForm,
    RedactorUpdateForm,
    UserRegisterForm
)


@login_required
def index(request: HttpRequest) -> HttpResponse:
    num_newspapers = Newspaper.objects.count()
    num_redactors = Redactor.objects.count()
    num_topics = Topic.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_newspapers": num_newspapers,
        "num_redactors": num_redactors,
        "num_topics": num_topics,
        "num_visits": num_visits
    }
    return render(request, "newspapers/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    paginate_by = 10

    def get_queryset(self) -> QuerySet:
        queryset = Topic.objects.all()
        form = TopicNameSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(TopicListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TopicNameSearchForm(
            initial={"name": name}
        )
        return context


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspapers:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspapers:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("newspapers:topic-list")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    paginate_by = 5

    def get_queryset(self) -> QuerySet:
        queryset = Newspaper.objects.prefetch_related('topics', 'publishers')
        form = NewspaperTitleSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(title__icontains=form.cleaned_data["title"])
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(NewspaperListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        context["search_form"] = NewspaperTitleSearchForm(
            initial={"title": title}
        )
        return context


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspapers:newspaper-list")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspapers:newspaper-list")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("newspapers:newspaper-list")


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    paginate_by = 10

    def get_queryset(self) -> QuerySet:
        queryset = Redactor.objects.all()
        form = RedactorUsernameSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(RedactorListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = RedactorUsernameSearchForm(
            initial={"username": username}
        )
        return context


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm
    success_url = reverse_lazy("newspapers:redactor-list")


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorUpdateForm
    success_url = reverse_lazy("newspapers:redactor-list")


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("newspapers:redactor-list")


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor

    def get_queryset(self) -> QuerySet:
        queryset = Redactor.objects.filter(
            id=self.kwargs["pk"]
        ).prefetch_related("newspapers")
        return queryset


class UserRegisterView(FormView):
    template_name = 'registration/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy("newspapers:index")

    def form_valid(self, form) -> HttpResponse:
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)

templates/newspapers/index.html
{% extends "base.html" %}
{% load static %}

{% block body %}index-page bg-gray-200{% endblock body %}

{% block content %}
  <header class="header-2">
    <div class="page-header min-vh-75 relative"
         style="background-image: url('{% static "assets/img/bg10.jpg" %}')">
      <span class="mask bg-gradient-dark opacity-4"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white font-weight-black pt-3 mt-n5">Newspaper Agency</h1>
            <p class="lead text-white mt-3">Newspaper Agency is a modern, responsive web application built using Django
              and Bootstrap 5. It offers a comprehensive UI kit and various pre-designed elements to help developers
              create stunning web pages efficiently.</p>
          </div>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
      <section class="pt-3 pb-4" id="count-stats">
        <div class="container">
          <div class="row">
            <div class="col-lg-9 mx-auto py-3">
              <div class="row">
                <div class="col-md-4 position-relative">
                  <div class="p-3 text-center">
                    <h1 class="text-gradient text-dark"><span id="state1" countTo="{{ num_newspapers }}">0</span>+</h1>
                    <h5 class="mt-3">Newspapers</h5>
                    <p class="text-sm font-weight-normal">From articles, to editorials, columns, and reports, you are
                      covered</p>
                  </div>
                  <hr class="vertical dark">
                </div>
                <div class="col-md-4 position-relative">
                  <div class="p-3 text-center">
                    <h1 class="text-gradient text-dark"><span id="state2" countTo="{{ num_redactors }}">0</span>+</h1>
                    <h5 class="mt-3">Redactors</h5>
                    <p class="text-sm font-weight-normal">Collaborate on articles, edit content, and bring your unique
                      voice to the publication.</p>
                  </div>
                  <hr class="vertical dark">
                </div>
                <div class="col-md-4">
                  <div class="p-3 text-center">
                    <h1 class="text-gradient text-dark" id="state3" countTo="{{ num_topics }}">0</h1>
                    <h5 class="mt-3">Topics</h5>
                    <p class="text-sm font-weight-normal">Explore a wide range of topics covered in our newspaper, from
                      current events to in-depth analyses.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
{% endblock %}

{% block extra_js %}

  <!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
  <script src="{% static "assets/js/plugins/countup.min.js" %}"></script>

  <script src="{% static "assets/js/plugins/choices.min.js" %}"></script>
  <script src="{% static "assets/js/plugins/prism.min.js" %}"></script>
  <script src="{% static "assets/js/plugins/highlight.min.js" %}"></script>

  <!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
  <script src="{% static "assets/js/plugins/rellax.min.js" %}"></script>
  <!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
  <script src="{% static "assets/js/plugins/tilt.min.js" %}"></script>
  <!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
  <script src="{% static "assets/js/plugins/choices.min.js" %}"></script>

  <script type="text/javascript">
      if (document.getElementById('state1')) {
          const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
          if (!countUp.error) {
              countUp.start();
          } else {
              console.error(countUp.error);
          }
      }
      if (document.getElementById('state2')) {
          const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
          if (!countUp1.error) {
              countUp1.start();
          } else {
              console.error(countUp1.error);
          }
      }
      if (document.getElementById('state3')) {
          const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
          if (!countUp2.error) {
              countUp2.start();
          } else {
              console.error(countUp2.error);
          }
      }
  </script>

{% endblock extra_js %}

templates/newspapers/newspaper_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block body %}index-page bg-gray-200{% endblock body %}

{% block content %}
  <header class="header-2">
    <div class="page-header min-vh-50 relative"
         style="background-image: url('{% static "assets/img/bg10.jpg" %}')">
      <span class="mask bg-gradient-dark opacity-4"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white font-weight-black pt-3 mt-n5">Newspapers</h1>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="container">
    <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
      <h1 class="p-2">
        Delete newspaper with title <span class="text-info">{{ newspaper.title }}</span>?
      </h1>
      <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes" class="btn btn-danger link-to-page">
        <button type="reset" onclick="goBack()" class="btn btn-secondary">Back</button>
      </form>
    </div>
  </div>
{% endblock %}

{% block extra_js %}
  <script>
      function goBack() {
          window.history.back();
      }
  </script>
{% endblock %}

templates/newspapers/newspaper_detail.html
{% extends 'base.html' %}
{% load static %}

{% block body %}index-page bg-gray-200{% endblock body %}

{% block content %}
  <header class="header-2">
    <div class="page-header min-vh-50 relative"
         style="background-image: url('{% static "assets/img/bg10.jpg" %}')">
      <span class="mask bg-gradient-dark opacity-4"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white font-weight-black pt-3 mt-n5">Newspapers</h1>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="container">
    <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
      <h1 class="p-2">
        {{ newspaper.title }}
        <a href="{% url 'newspapers:newspaper-update' pk=newspaper.id %}" class="btn btn-primary link-to-page">
          Update
        </a>
        <a href="{% url 'newspapers:newspaper-delete' pk=newspaper.id %}" class="btn btn-danger link-to-page">
          Delete
        </a>
      </h1>
      <p>{{ newspaper.content }}</p>
      <p class="author-decor">
        Authors:
        {% for author in newspaper.publishers.all %}
          <a href="{% url 'newspapers:redactor-detail' pk=author.id %}">{{ author.first_name }} {{ author.last_name }}</a>
          ,
        {% endfor %}
      </p>
      <p class="date">
        Published date: {{ newspaper.published_date }}
      </p>
    </div>
  </div>
{% endblock %}

templates/newspapers/newspaper_form.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}
{% load crispy_forms_filters %}

{% block body %}index-page bg-gray-200{% endblock body %}

{% block extra_style %}
  <style>
      .form-control, .form-select {
          border: 1px solid #dee2e6 !important;
          padding: 8px;
      }
  </style>
{% endblock %}

{% block content %}
  <header class="header-2">
    <div class="page-header min-vh-50 relative"
         style="background-image: url('{% static "assets/img/bg10.jpg" %}')">
      <span class="mask bg-gradient-dark opacity-4"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white font-weight-black pt-3 mt-n5">Newspapers</h1>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="container">
    <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
      <h1 class="p-2">{{ object|yesno:"Update,Create" }} newspaper</h1>
      <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit" class="btn btn-primary">
      </form>
    </div>
  </div>
{% endblock %}

templates/newspapers/newspaper_list.html
{% extends "base.html" %}
{% load static %}

{% block body %}index-page bg-gray-200{% endblock body %}

{% block content %}
  <header class="header-2">
    <div class="page-header min-vh-50 relative"
         style="background-image: url('{% static "assets/img/bg10.jpg" %}')">
      <span class="mask bg-gradient-dark opacity-4"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white font-weight-black pt-3 mt-n5">Newspapers</h1>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="container">
    <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
      <h1 class="p-2">
        Newspaper list
        <a href="{% url 'newspapers:newspaper-create' %}" class="btn btn-primary link-to-page">
          Create
        </a>
      </h1>
      <div class="col-12 col-md-6 col-xl-4 mt-2 mx-2">
        {% include "includes/search_form.html" %}
      </div>
      {% if newspaper_list %}
        <section class="pb-2">
          <div class="row">
            {% for newspaper in newspaper_list %}
              <div class="col-lg-12">
                <div class="row">
                  <div class="col-12 justify-content-center d-flex flex-column ps-lg-5 pt-lg-0 pt-3">
                    <h6 class="category text-info mt-3">
                      {% for topic in newspaper.topics.all %}
                        {{ topic.name }}
                      {% endfor %}
                    </h6>
                    <h3>
                      <a href="{% url 'newspapers:newspaper-update' pk=newspaper.id %}"
                         class="text-dark">{{ newspaper.title }}</a>
                    </h3>
                    <p>{{ newspaper.content|truncatewords:30 }}
                      <a href="{% url 'newspapers:newspaper-detail' pk=newspaper.id %}"
                         class="text-darker icon-move-right text-sm">Read More
                        <i class="fas fa-arrow-right text-xs ms-1"></i>
                      </a>
                    </p>
                    <p class="author">
                      by
                      {% for author in newspaper.publishers.all %}
                        <a href="{% url 'newspapers:redactor-detail' pk=author.id %}" class="ms-1">
                          <span class="font-weight-bold text-info">
                            {{ author.first_name }} {{ author.last_name }}
                          </span>
                        </a>,
                      {% endfor %}
                      {{ newspaper.published_date }}
                    </p>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </section>
      {% else %}
        <p>There are no newspapers in newspaper agency</p>
      {% endif %}
      {% include 'includes/pagination.html' %}
    </div>
  </div>
{% endblock %}

templates/newspapers/redactor_detail.html
{% extends 'base.html' %}
{% load static %}

{% block body %}index-page bg-gray-200{% endblock body %}

{% block content %}
  <header class="header-2">
    <div class="page-header min-vh-50 relative"
         style="background-image: url('{% static "assets/img/bg10.jpg" %}')">
      <span class="mask bg-gradient-dark opacity-4"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white font-weight-black pt-3 mt-n5">Redactors</h1>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="container">
    <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
      <h1 class="p-2">
        {{ redactor.username }}
        <a href="{% url 'newspapers:redactor-update' pk=redactor.id %}" class="btn btn-primary link-to-page">
          Update
        </a>
        <a href="{% url 'newspapers:redactor-delete' pk=redactor.id %}" class="btn btn-danger link-to-page">
          Delete
        </a>
      </h1>
      <p>Full name: <span class="text-dark">{{ redactor.first_name }} {{ redactor.last_name }}</span></p>
      <p>Email: <span class="text-dark">{{ redactor.email }}</span></p>
      <p>Years of experience: <span class="text-dark">{{ redactor.years_of_experience }}</span></p>
      <p>
        {% if redactor.newspapers.all %}
          Newspapers:
          {% for newspaper in redactor.newspapers.all %}
            <a href="{% url 'newspapers:newspaper-detail' pk=newspaper.id %}">{{ newspaper.title }}</a>,
          {% endfor %}
        {% else %}
          This author has not written any newspapers
        {% endif %}
      </p>
    </div>
  </div>
{% endblock %}

templates/newspapers/redactor_list.html
{% extends "base.html" %}
{% load static %}

{% block body %}index-page bg-gray-200{% endblock body %}

{% block content %}
  <header class="header-2">
    <div class="page-header min-vh-50 relative"
         style="background-image: url('{% static "assets/img/bg10.jpg" %}')">
      <span class="mask bg-gradient-dark opacity-4"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white font-weight-black pt-3 mt-n5">Redactors</h1>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="container">
    <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
      <h1 class="p-2">
        Redactor list
        <a href="{% url 'newspapers:redactor-create' %}" class="btn btn-primary link-to-page">
          Create
        </a>
      </h1>
      <div class="col-12 col-md-6 col-xl-4 mt-2 mx-2">
        {% include "includes/search_form.html" %}
      </div>
      {% if redactor_list %}
        <div class="row justify-content-center mb-4">
          <div class="col-lg-12">
            <div class="card border-0">
              <div class="table-responsive">
                <table class="table align-items-center mb-0">
                  <thead>
                  <tr>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Username</th>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Full name</th>
                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                      Email
                    </th>
                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                      Years of experience
                    </th>
                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                      Update
                    </th>
                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                      Delete
                    </th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for redactor in redactor_list %}
                    <tr>
                      <td>
                        <div class="d-flex px-2 py-1">
                          <div class="d-flex flex-column justify-content-center">
                            <h6 class="mb-0 text-xs">
                              <a class="text-decoration-underline"
                                 href="{% url 'newspapers:redactor-detail' pk=redactor.id %}">
                                {{ redactor.username }}
                              </a>
                            </h6>
                          </div>
                        </div>
                      </td>
                      <td>
                        <p class="text-xs font-weight-bold mb-0">{{ redactor.first_name }} {{ redactor.last_name }}</p>
                      </td>
                      <td class="align-middle text-center text-sm">
                        <p class="text-xs font-weight-bold mb-0">{{ redactor.email }}</p>
                      </td>
                      <td class="align-middle text-center">
                        <span class="text-secondary text-xs font-weight-bold">{{ redactor.years_of_experience }}</span>
                      </td>
                      <td class="align-middle text-center">
                        <a href="{% url 'newspapers:redactor-update' pk=redactor.id %}"
                           class="text-secondary font-weight-bold text-xs" data-toggle="tooltip"
                           data-original-title="Edit user">
                          Edit
                        </a>
                      </td>
                      <td class="align-middle text-center">
                        <a href="{% url 'newspapers:redactor-delete' pk=redactor.id %}"
                           class="text-secondary font-weight-bold text-xs" data-toggle="tooltip"
                           data-original-title="Edit user">
                          Delete
                        </a>
                      </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      {% else %}
        <p>There are no redactors in newspaper agency</p>
      {% endif %}
      {% include 'includes/pagination.html' %}
    </div>
  </div>
{% endblock %}

templates/newspapers/topic_list.html
{% extends "base.html" %}
{% load static %}

{% block body %}index-page bg-gray-200{% endblock body %}

{% block content %}
  <header class="header-2">
    <div class="page-header min-vh-50 relative"
         style="background-image: url('{% static "assets/img/bg10.jpg" %}')">
      <span class="mask bg-gradient-dark opacity-4"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white font-weight-black pt-3 mt-n5">Topics</h1>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="container">
    <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
      <h1 class="p-2">
        Topic list
        <a href="{% url 'newspapers:topic-create' %}" class="btn btn-primary link-to-page">
          Create
        </a>
      </h1>
      <div class="col-12 col-md-6 col-xl-4 mt-2 mx-2">
        {% include "includes/search_form.html" %}
      </div>
      {% if topic_list %}
        <div>
          {% for topic in topic_list %}
            <p><span class="text text-4xl text-info user-select-none">{{ topic.id }}</span> <span
                class="text text-4xl text-dark">{{ topic.name }}</span>
              <a class="btn btn-primary" href="{% url 'newspapers:topic-update' pk=topic.id %}">Update</a>
              <a class="btn btn-danger" href="{% url 'newspapers:topic-delete' pk=topic.id %}">Delete</a>
            </p>
          {% endfor %}
        </div>
      {% else %}
        <p>There are no topics in newspaper agency</p>
      {% endif %}
      {% include 'includes/pagination.html' %}
    </div>
  </div>
{% endblock %}