newspapers/urls.py
from django.urls import path

from newspapers.views import (
    index,
    TopicCreateView,
    TopicListView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperListView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorListView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDeleteView,
    NewspaperDetailView,
    RedactorDetailView
)

urlpatterns = [
    path("", index, name="index"),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
    path("topics/<int:pk>/update/", TopicUpdateView.as_view(), name="topic-update"),
    path("topics/<int:pk>/delete/", TopicDeleteView.as_view(), name="topic-delete"),
    path("newspapers/", NewspaperListView.as_view(), name="newspaper-list"),
    path("newspapers/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path("newspapers/<int:pk>/update/", NewspaperUpdateView.as_view(), name="newspaper-update"),
    path("newspapers/<int:pk>/delete/", NewspaperDeleteView.as_view(), name="newspaper-delete"),
    path("newspapers/<int:pk>/", NewspaperDetailView.as_view(), name="newspaper-detail"),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path("redactors/create/", RedactorCreateView.as_view(), name="redactor-create"),
    path("redactors/<int:pk>/update/", RedactorUpdateView.as_view(), name="redactor-update"),
    path("redactors/<int:pk>/delete/", RedactorDeleteView.as_view(), name="redactor-delete"),
    path("redactors/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"),
]

app_name = "newspapers"

templates/includes/footer-transparent.html
<footer class="footer position-absolute bottom-2 py-2 w-100">
  <div class="container">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col-12 col-md-6 my-auto">
        <div class="copyright text-center text-sm text-white text-lg-start">
          © Created by <a href="https://github.com/zave52" class="font-weight-bold text-white">zave</a>.
        </div>
      </div>
      <div class="col-12 col-md-6">
        <ul class="nav nav-footer justify-content-center justify-content-lg-end">
          <li class="nav-item">
            <a href="https://github.com/zave52/Newspaper-Agency" class="nav-link text-white">Repository</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

templates/includes/footer.html
<footer class="footer pt-3 mt-3">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-sm-4 col-6 mb-4 d-flex align-items-center">
        <div>
          <a href="{% url 'newspapers:index' %}">
            <h6 class="font-weight-bolder mb-4">Newspaper Agency</h6>
          </a>
        </div>
      </div>

      <div class="col-sm-4 col-6 mb-4">
        <div>
          <h6 class="text-sm">Sections</h6>
          <ul class="flex-column ms-n3 nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'newspapers:newspaper-list' %}">
                Newspapers
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'newspapers:redactor-list' %}">
                Redactors
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'newspapers:topic-list' %}">
                Topics
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="col-12">
      <div class="text-center">
        <p class="text-dark my-4 text-sm font-weight-normal">
          &copy; Created by <a href="https://github.com/zave52" class="font-weight-bold">zave</a>.
        </p>
      </div>
    </div>
  </div>
</footer>

templates/includes/head.html
{% load static %}

<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>Newspaper Agency</title>

<!--     Fonts and icons     -->
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700,900"/>

<!-- Nucleo Icons -->
<link href="{% static "assets/css/nucleo-icons.css" %}" rel="stylesheet"/>
<link href="{% static "assets/css/nucleo-svg.css" %}" rel="stylesheet"/>

<!-- Font Awesome Icons -->
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.0/js/all.min.js"
        crossorigin="anonymous"></script>

<!-- Material Icons -->
<link rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0"/>

<!-- CSS Files -->
<link id="pagestyle" href="{% static "assets/css/material-kit.css" %}?v=3.1.0" rel="stylesheet"/>

templates/includes/navigation-transparent.html
{% load static %}


<nav class="navbar navbar-expand-lg position-absolute top-0 z-index-3 w-100 shadow-none my-3  navbar-transparent ">
  <div class="container">
    <a class="navbar-brand  text-white " href="{% url "newspapers:index" %}" rel="tooltip"
       data-placement="bottom">
      Newspaper Agency
    </a>
    <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation"
            aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon mt-2">
          <span class="navbar-toggler-bar bar1"></span>
          <span class="navbar-toggler-bar bar2"></span>
          <span class="navbar-toggler-bar bar3"></span>
        </span>
    </button>
    <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
      <ul class="navbar-nav navbar-nav-hover ms-auto">
        <li class="nav-item mx-2">
          <a href="{% url 'newspapers:newspaper-list' %}"
             class="nav-link ps-2 d-flex cursor-pointer align-items-center font-weight-semibold">
            Newspapers
          </a>
        </li>
        <li class="nav-item mx-2">
          <a href="{% url 'newspapers:redactor-list' %}"
             class="nav-link ps-2 d-flex cursor-pointer align-items-center font-weight-semibold">
            Redactors
          </a>
        </li>
        <li class="nav-item mx-2">
          <a href="{% url 'newspapers:topic-list' %}"
             class="nav-link ps-2 d-flex cursor-pointer align-items-center font-weight-semibold">
            Topics
          </a>
        </li>

        {% if request.user.is_authenticated %}
          <li class="nav-item ms-lg-auto">
            <form id="logout-form" method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit" class="nav-link nav-link-icon me-2 d-inline text-sm z-index-1 font-weight-semibold"
                      data-bs-toggle="tooltip"
                      data-bs-placement="bottom">
                <i class="fa fa-sign-out me-1"></i>
                Logout
              </button>
            </form>
          </li>
        {% else %}
          <li class="nav-item ms-lg-auto">
            <a class="nav-link nav-link-icon me-2" href="{% url 'login' %}">
              <i class="fa fa-sign-in me-1"></i>
              <p class="d-inline text-sm z-index-1 font-weight-semibold" data-bs-toggle="tooltip"
                 data-bs-placement="bottom" title="Sign in">Sign in</p>
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/includes/navigation.html
{% load static %}

<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav
          class="navbar navbar-expand-lg  blur border-radius-xl top-0 z-index-fixed shadow position-absolute my-3 p-2 start-0 end-0 mx-4">
        <div class="container-fluid px-0">
          <a class="navbar-brand font-weight-bolder ms-sm-3 text-sm"
             href="{% url "newspapers:index" %}" rel="tooltip" data-placement="bottom">
            Newspaper Agency
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"
                  data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"
                  aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-auto">
              <li class="nav-item mx-2">
                <a href="{% url 'newspapers:newspaper-list' %}"
                   class="nav-link ps-2 d-flex cursor-pointer align-items-center font-weight-semibold">
                  Newspapers
                </a>
              </li>
              <li class="nav-item mx-2">
                <a href="{% url 'newspapers:redactor-list' %}"
                   class="nav-link ps-2 d-flex cursor-pointer align-items-center font-weight-semibold">
                  Redactors
                </a>
              </li>
              <li class="nav-item mx-2">
                <a href="{% url 'newspapers:topic-list' %}"
                   class="nav-link ps-2 d-flex cursor-pointer align-items-center font-weight-semibold">
                  Topics
                </a>
              </li>
              {% if request.user.is_authenticated %}
                <li class="nav-item ms-lg-auto">
                  <form id="logout-form" method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit"
                            class="nav-link nav-link-icon me-2 d-inline text-sm z-index-1 font-weight-semibold"
                            data-bs-toggle="tooltip"
                            data-bs-placement="bottom">
                      <i class="fa fa-sign-out me-1"></i>
                      Logout
                    </button>
                  </form>
                </li>
              {% else %}
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2" href="{% url 'login' %}">
                    <i class="fa fa-sign-in me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-semibold" data-bs-toggle="tooltip"
                       data-bs-placement="bottom" title="Sign in">Sign in</p>
                  </a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
  <div class="row justify-space-between py-2">
    <div class="col-lg-4 mx-auto">
      <ul class="pagination pagination-primary m-4 justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}"
               aria-label="Previous">
              <span aria-hidden="true"><i class="material-symbols-rounded" aria-hidden="true">chevron_left</i></span>
            </a>
          </li>
        {% endif %}
        {% for page_num in page_obj.paginator.page_range %}
          {% if page_num == page_obj.number %}
            <li class="page-item active">
              <span class="page-link">{{ page_num }}</span>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?{% query_transform request page=page_num %}">{{ page_num }}</a>
            </li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}" aria-label="Next">
              <span aria-hidden="true"><i class="material-symbols-rounded" aria-hidden="true">chevron_right</i></span>
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
{% endif %}

templates/includes/scripts.html
{% load static %}

<!--   Core JS Files   -->
<script src="{% static "assets/js/core/popper.min.js" %}" type="text/javascript"></script>
<script src="{% static "assets/js/core/bootstrap.min.js" %}" type="text/javascript"></script>
<script src="{% static "assets/js/plugins/perfect-scrollbar.min.js" %}"></script>

<!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
<!--  Google Maps Plugin    -->

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
<script src="{% static "assets/js/material-kit.min.js" %}?v=3.1.0" type="text/javascript"></script>

templates/includes/search_form.html
{% load custom_filters %}

<form class="input-group input-group-dynamic mb-4" method="get" action="">
  {% for field in search_form %}
    {{ field|add_class:"form-control mb-4" }}
  {% endfor %}
  <input class="btn btn-secondary w-auto me-2 mb-4" type="submit" value="🔎">
</form>